apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: test-1
    fabien/toto: test-1
  labels:
    app: hello
  name: hello
spec:
  replicas: 30
  selector:
    matchLabels:
      app: hello
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - image: bob2606/hello-http:0.8.25
          name: hello-http
          env:
            - name: STAGE
              value: K9S
          envFrom:
            - configMapRef:
                name: hello
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 2
            failureThreshold: 2
          ports:
            - name: http
              containerPort: 80
