apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - image: bob2606/hello-http:0.8.25
          name: hello-http
          envFrom:
            - configMapRef:
                name: hello
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            periodSeconds: 2
            failureThreshold: 2
          ports:
            - name: http
              containerPort: 80
