apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: hello
  name: hello
spec:
  replicas: 3
  serviceName: hello
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      initContainers:
        - image: busybox:1.28
          name: busy
          command:
            - /bin/sh
          args:
            - -c
            - |
              idx=$(hostname|cut -d- -f2)
              if [ $idx = "0" ]
              then
                echo "Principal" > /tmp/status
              else
                echo "Secondaire n°$idx" > /tmp/status
              fi
          volumeMounts:
            - name: status
              mountPath: /tmp
      containers:
        - image: bob2606/hello-http:0.8.25
          name: hello-http
          env:
            - name: PORT
              value: "80"
            - name: SERVICE
              value: hello
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: status
              mountPath: /var/lib/hello-http/

      volumes:
        - name: status
          emptyDir:
