apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.26
        name: nginx
        ports:
          - name: http
            containerPort: 80
        env:
          - name: STAGE
            value: Kubernetes
          - name: JOURS
            value: "5"
          - name: NODEIP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: URL
            valueFrom:
              configMapKeyRef:
                name: nginx
                key: NGINX_URL
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: nginx
                key: PASSWORD
      - image: php:8.2-fpm
        name: php
