apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
    nodePort: 31000
  type: NodePort
  selector:
    app: nginx
