apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.26
        name: nginx
        ports:
          - name: http
            containerPort: 80
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          periodSeconds: 3
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          periodSeconds: 10
          failureThreshold: 2
        volumeMounts:
          - name: data
            mountPath: /usr/share/nginx/html
            subPath: site-nginx
          - name: conf-nginx
            mountPath: /etc/nginx/conf.d

      - image: php:8.2-fpm
        name: php
        volumeMounts:
          - name: data
            mountPath: /var/www/html
            subPath: site-nginx
      volumes:
        - name: data
          hostPath:
            path: /data
            type: Directory
        - name: conf-nginx
          configMap:
            name: nginx
