apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: bob
spec:
  request: 
  signerName: kubernetes.io/kube-api-server-client
  expirationSeconds: 86400
  usages:
    - client auth
